/*--------------------------------------------------------------------------------------------------
-- SOURCE FILE: main.cpp - The entry point of the application. 
--
-- PROGRAM: dcTerm (Data Communication Terminal)
--
-- FUNCTIONS:
-- void main(int argc, char* argv[]);
--
-- DATE: September 29, 2017
--
-- REVISIONS: N/A
--
-- DESIGNER: The Qt Company 
--
-- PROGRAMMER: The Qt Company 
--
-- NOTES:
-- The main entry point of the application. This file is automatically generated when starting a
-- Qt GUI application.
--------------------------------------------------------------------------------------------------*/
#include "dcTerm.h"
#include <QtWidgets/QApplication>

/*--------------------------------------------------------------------------------------------------
-- FUNCTION: main
--
-- DATE: September 29, 2017
--
-- REVISIONS: N/A
--
-- DESIGNER: The Qt Company 
--
-- PROGRAMMER: The Qt Company 
--
-- INTERFACE: main (int argc, char* argv[])
--
-- NOTES:
-- The entry point of the program.
-- Creates a QApplication that is untouched by the developer and a developer defined dcTerm object.
--------------------------------------------------------------------------------------------------*/
int main(int argc, char* argv[])
{
	QApplication a(argc, argv);
	dcTerm w;
	w.show();
	return a.exec();
}
